package echatapp;


import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import java.util.HashMap;

public class ChatOptions extends javax.swing.JPanel {

    /**
     * Creates new form ChatOptions
     */
    public ChatOptions() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SendMButton = new javax.swing.JButton();
        RecentMButton = new javax.swing.JButton();
        QuitButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 102, 102));

        SendMButton.setBackground(new java.awt.Color(255, 255, 255));
        SendMButton.setForeground(new java.awt.Color(0, 0, 0));
        SendMButton.setText("1. Send Messages");
        SendMButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        SendMButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendMButtonActionPerformed(evt);
            }
        });

        RecentMButton.setBackground(new java.awt.Color(255, 255, 255));
        RecentMButton.setForeground(new java.awt.Color(0, 0, 0));
        RecentMButton.setText("2. Show Recenlty sent messages");
        RecentMButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecentMButtonActionPerformed(evt);
            }
        });

        QuitButton.setBackground(new java.awt.Color(255, 255, 255));
        QuitButton.setForeground(new java.awt.Color(0, 0, 0));
        QuitButton.setText("3. Quit");
        QuitButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        QuitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuitButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(" EChat App Menu");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(QuitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(RecentMButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SendMButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(140, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(SendMButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(RecentMButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(QuitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        SendMButton.getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    private void SendMButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendMButtonActionPerformed
        // TODO add your handling code here:
        SwingUtilities.getWindowAncestor(this).dispose();
        // While loop for the application
        while(true){
            // try and catch for exceptional handling
        try {
            String numMessagesStr = JOptionPane.showInputDialog("How many messages would you like to send?");
            if(numMessagesStr == null) {
                return; // User canceled
            }
           
            int numMessages = Integer.parseInt(numMessagesStr);
           // For loop to allow users to enter the assigned number of messages
            for (int i = 0; i < numMessages; i++) {
                // Get message details
                String recipient = JOptionPane.showInputDialog("Enter recipient's cell number (including + international code):");
                if (recipient == null) {
                    break; // User canceled
                }
                
                Message message1 = new Message();
               int valid = message1.checkRecipientCell(recipient);
               
               if(valid == 0){
                   JOptionPane.showMessageDialog(null, "Invalid recipient number. Must be maximum 10 characters and start with +");
                   break;
               }

               
                String messageContent = JOptionPane.showInputDialog("Enter your message (max 250 characters):");
                if (messageContent == null) {
                    break; // User canceled
                }
               
                if (messageContent.length() > 250) {
                    JOptionPane.showMessageDialog(null, "Please enter a message of less than 250 characters.");
                    i--; // Retry this message
                    continue;
                }
               
                // Create and process the message
                Message message = new Message(recipient, messageContent);
               
                if (message.checkRecipientCell() == 0) {
                    JOptionPane.showMessageDialog(null, "Invalid recipient number. Must be maximum 10 characters and start with +");
                    i--; // Retry this message
                    continue;
                }
               
                // Process the message
               // Show message details before the options dialog
               String messageDetails = "MessageID: " + message.getMessageID() +
                      "\nMessage Hash: " + message.getMessageHash() +
                      "\nRecipient: " + message.getRecipient() +
                      "\nMessage: " + message.getMessageContent();

                JOptionPane.showMessageDialog(null, messageDetails);

               // Now show the options dialog and get the result
               String result = message.sentMessage();
               JOptionPane.showMessageDialog(null, result);
               
               // Show message details AGAIN ONLY if the message was sent
            if (result.equals("Message sent")) {
               JOptionPane.showMessageDialog(null, "Sent Message Details:\n" + messageDetails);
            }
        }
            // Show total messages sent
               JOptionPane.showMessageDialog(null, "Total messages sent: " + Message.returnTotalMessages());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please enter a valid number.");
        }
        }
    }//GEN-LAST:event_SendMButtonActionPerformed

    private void QuitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuitButtonActionPerformed
        // TODO add your handling code here:
        SwingUtilities.getWindowAncestor(this).dispose();
    }//GEN-LAST:event_QuitButtonActionPerformed

    private void RecentMButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecentMButtonActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Coming Soon.");
    }//GEN-LAST:event_RecentMButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton QuitButton;
    private javax.swing.JButton RecentMButton;
    private javax.swing.JButton SendMButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
