package echatapp;

import javax.swing.*;
import javax.swing.SwingUtilities;

public class LoginPage extends javax.swing.JPanel { 
       public LoginPage (){
       initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UserLabel = new javax.swing.JLabel();
        PassLabel = new javax.swing.JLabel();
        UseName = new javax.swing.JTextField();
        ShowPassCheckBox = new javax.swing.JCheckBox();
        LoginButton = new javax.swing.JButton();
        VerifyCheckBox = new javax.swing.JCheckBox();
        PasswordField = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        RegButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 102, 102));
        setForeground(new java.awt.Color(0, 102, 102));

        UserLabel.setForeground(new java.awt.Color(255, 255, 255));
        UserLabel.setText("Username :");

        PassLabel.setForeground(new java.awt.Color(255, 255, 255));
        PassLabel.setText("Password :");

        UseName.setBackground(new java.awt.Color(255, 255, 255));
        UseName.setBorder(null);
        UseName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UseNameActionPerformed(evt);
            }
        });

        ShowPassCheckBox.setBackground(new java.awt.Color(0, 102, 102));
        ShowPassCheckBox.setForeground(new java.awt.Color(255, 255, 255));
        ShowPassCheckBox.setText("Show Password");
        ShowPassCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowPassCheckBoxActionPerformed(evt);
            }
        });

        LoginButton.setBackground(new java.awt.Color(255, 255, 255));
        LoginButton.setForeground(new java.awt.Color(0, 0, 0));
        LoginButton.setText("Login");
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });

        VerifyCheckBox.setBackground(new java.awt.Color(0, 102, 102));
        VerifyCheckBox.setForeground(new java.awt.Color(255, 255, 255));
        VerifyCheckBox.setText("Verify");
        VerifyCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerifyCheckBoxActionPerformed(evt);
            }
        });

        PasswordField.setBackground(new java.awt.Color(255, 255, 255));
        PasswordField.setForeground(new java.awt.Color(0, 0, 0));
        PasswordField.setBorder(null);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Don't Have Account ?");

        RegButton.setBackground(new java.awt.Color(255, 255, 255));
        RegButton.setForeground(new java.awt.Color(0, 0, 0));
        RegButton.setText("Sign Up");
        RegButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegButtonActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(0, 102, 102));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Login Page ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(UserLabel)
                    .addComponent(PassLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(ShowPassCheckBox)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                            .addComponent(VerifyCheckBox))
                        .addComponent(UseName, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RegButton))
                    .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 137, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(LoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UserLabel))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PassLabel)
                    .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ShowPassCheckBox)
                    .addComponent(VerifyCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(RegButton))
                .addGap(34, 34, 34)
                .addComponent(LoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(106, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void UseNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UseNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UseNameActionPerformed

    private void ShowPassCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowPassCheckBoxActionPerformed
       if (ShowPassCheckBox.isSelected()) {
        PasswordField.setEchoChar((char) 0); // Show
    } else {
        PasswordField.setEchoChar('*'); // Hide
    }
    }//GEN-LAST:event_ShowPassCheckBoxActionPerformed

    private void VerifyCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerifyCheckBoxActionPerformed
        // TODO add your handling code here:  
    }//GEN-LAST:event_VerifyCheckBoxActionPerformed

       @SuppressWarnings("empty-statement")
    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
    String username = UseName.getText().trim();
    String password = new String(PasswordField.getPassword()).trim();
    
    Login login = new Login(username, password);
    boolean loginSuccess = login.loginUser(username, password);
    if (!VerifyCheckBox.isSelected()) {
        JOptionPane.showMessageDialog(this, "Please verify before logging in.");
        return;
    }
    if (username.isEmpty() || password.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Username and password cannot be empty.");
        return;
    }
    // Validate user input
    if (loginSuccess) {
        //JOptionPane.showMessageDialog(null, "Welcome To EChat App.");//
        JFrame LogFrame = new JFrame ("Chats");
        LogFrame.setContentPane(new ChatOptions());
        LogFrame.setSize(400 ,300);
        LogFrame.setLocationRelativeTo(null);
        LogFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        LogFrame.setVisible(true);
        SwingUtilities.getWindowAncestor(this).dispose();
    } else {
        JOptionPane.showMessageDialog(this, "Invalid username or password.");
       
      };
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void RegButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegButtonActionPerformed
        // TODO add your handling code here:
       JFrame RegFrame = new JFrame ("Registration");
       RegFrame.setContentPane(new RegistrationPage());
       RegFrame.setSize(408,431);
       RegFrame.setLocationRelativeTo(null);
       RegFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
       RegFrame.setVisible(true);
       SwingUtilities.getWindowAncestor(this).dispose();
    }//GEN-LAST:event_RegButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LoginButton;
    private javax.swing.JLabel PassLabel;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JButton RegButton;
    private javax.swing.JCheckBox ShowPassCheckBox;
    private javax.swing.JTextField UseName;
    private javax.swing.JLabel UserLabel;
    private javax.swing.JCheckBox VerifyCheckBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
